-- Crear tabla de Mesas
CREATE TABLE IF NOT EXISTS public.mesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER UNIQUE NOT NULL,
    estado VARCHAR(50) DEFAULT 'libre' CHECK (estado IN ('libre', 'ocupada', 'esperando_pedido', 'atendida')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear tabla de Categorías de Productos
CREATE TABLE IF NOT EXISTS public.categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear tabla de Productos (Menú)
CREATE TABLE IF NOT EXISTS public.productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT REFERENCES public.categorias(id) ON DELETE SET NULL,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT,
    precio NUMERIC(10, 2) NOT NULL,
    imagen_url TEXT,
    disponible BOOLEAN DEFAULT TRUE,
    es_cafe BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear tabla de Pedidos (tanto para mesa como para delivery)
CREATE TABLE IF NOT EXISTS public.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('mesa', 'delivery')),
    mesa_id BIGINT REFERENCES public.mesas(id) ON DELETE SET NULL,
    nombre_cliente VARCHAR(100),
    telefono VARCHAR(50),
    direccion TEXT, -- Solo para delivery
    estado VARCHAR(50) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'preparando', 'listo', 'entregado', 'cancelado')),
    total NUMERIC(10, 2) DEFAULT 0.00 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear tabla de Detalles de Pedido (Productos ordenados)
CREATE TABLE IF NOT EXISTS public.detalles_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT REFERENCES public.pedidos(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES public.productos(id) ON DELETE SET NULL,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(10, 2) NOT NULL,
    observaciones TEXT, -- Ej: "cortado con leche de almendras", "sin azúcar"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear tabla de Solicitudes de Mesa (Llamados al mozo o cuenta)
CREATE TABLE IF NOT EXISTS public.solicitudes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id BIGINT REFERENCES public.mesas(id) ON DELETE CASCADE NOT NULL,
    tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('llamar_mozo', 'pedir_cuenta')),
    estado VARCHAR(50) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'atendida')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Realtime para las tablas clave
-- NOTA: Si ya están añadidas, ejecutar ALTER PUBLICATION individualmente o recrear
ALTER PUBLICATION supabase_realtime ADD TABLE public.pedidos;
ALTER PUBLICATION supabase_realtime ADD TABLE public.mesas;
ALTER PUBLICATION supabase_realtime ADD TABLE public.detalles_pedido;
ALTER PUBLICATION supabase_realtime ADD TABLE public.solicitudes;
